/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AudioMetrics {
  'phaseDrift' : number,
  'amplitude' : number,
  'frequency' : number,
  'entropyNoise' : number,
}
export interface CrossChainEvent {
  'timestamp' : bigint,
  'details' : string,
  'eventType' : string,
}
export interface CrossChainMetrics {
  'chi' : number,
  'phi' : number,
  'theta' : number,
  'inv1' : boolean,
  'inv2' : boolean,
  'inv3' : boolean,
  'inv4' : boolean,
  'inv5' : boolean,
  'inv6' : boolean,
  'chronoflux' : number,
  'rhoAsi' : number,
  'rhoEth' : number,
}
export interface CymaticParameters {
  'uniformData' : Array<number>,
  'visualPattern' : string,
  'intensity' : number,
}
export interface DHTMetrics {
  'dhtScore' : number,
  'merkleVerified' : boolean,
  'nodeCount' : bigint,
}
export interface EthereumAgent {
  'checksumValid' : boolean,
  'address' : string,
  'dhtMetrics' : DHTMetrics,
  'entropyScore' : number,
}
export interface HumanMetrics {
  'sandboxActive' : boolean,
  'intentConfidence' : number,
  'phiDeviation' : number,
  'cognitiveLoad' : number,
}
export interface MerkabahSolar {
  'chiHermetica' : number,
  'tetraedroFeminino' : Vector3D,
  'autisticContinuum' : boolean,
  'tetraedroMasculino' : Vector3D,
  'ar4366Flux' : number,
}
export interface Node {
  'id' : string,
  'status' : NodeStatus,
  'location' : string,
}
export type NodeStatus = { 'active' : null } |
  { 'voting' : null } |
  { 'inactive' : null } |
  { 'participating' : null };
export interface Proposal {
  'id' : bigint,
  'status' : ProposalStatus,
  'title' : string,
  'content' : string,
  'votes' : Array<Vote>,
  'proposer' : Principal,
}
export type ProposalStatus = { 'noConsensus' : null } |
  { 'pending' : null } |
  { 'crossChainConsensus' : null } |
  { 'voting' : null } |
  { 'approved' : null } |
  { 'tmrConsensus' : null } |
  { 'rejected' : null } |
  { 'majorityConsensus' : null };
export interface TVBroadcastMetrics {
  'broadcastId' : bigint,
  'nodeId' : string,
  'frameRate' : number,
  'amplitude' : number,
  'entropy' : number,
  'transmissionQuality' : number,
  'bleStatus' : boolean,
  'phiIntegrity' : number,
  'timestamp' : bigint,
  'frequency' : number,
  'tmrValidation' : boolean,
  'pqcStatus' : boolean,
}
export interface TVBroadcastSummary {
  'status' : string,
  'broadcastId' : bigint,
  'signalStrength' : number,
  'nodeId' : string,
  'transmissionQuality' : number,
}
export interface UserProfile { 'nodeId' : [] | [string], 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vector3D { 'x' : number, 'y' : number, 'z' : number }
export interface Vote { 'nodeId' : string, 'accepted' : boolean }
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'activateMerkabahSolar' : ActorMethod<[number], number>,
  'addEthereumAgent' : ActorMethod<[string, number, boolean], undefined>,
  'addNode' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProposal' : ActorMethod<[string, string], bigint>,
  'generateCymaticParameters' : ActorMethod<[AudioMetrics], CymaticParameters>,
  'getAllNodes' : ActorMethod<[], Array<Node>>,
  'getAllProposals' : ActorMethod<[], Array<Proposal>>,
  'getAllProposalsByTitle' : ActorMethod<[], Array<Proposal>>,
  'getAudioMetrics' : ActorMethod<[Principal], AudioMetrics>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCrossChainEvents' : ActorMethod<[], Array<CrossChainEvent>>,
  'getCrossChainEventsByType' : ActorMethod<[string], Array<CrossChainEvent>>,
  'getCrossChainMetrics' : ActorMethod<[], CrossChainMetrics>,
  'getCurrentTVBroadcastSummaries' : ActorMethod<[], Array<TVBroadcastSummary>>,
  'getCymaticParameters' : ActorMethod<[Principal], CymaticParameters>,
  'getEthereumAgent' : ActorMethod<[string], EthereumAgent>,
  'getHumanMetrics' : ActorMethod<[Principal], HumanMetrics>,
  'getMerkabahSolarParams' : ActorMethod<[], MerkabahSolar>,
  'getNode' : ActorMethod<[string], Node>,
  'getProposal' : ActorMethod<[bigint], Proposal>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logCrossChainEvent' : ActorMethod<[string, string], undefined>,
  'pruneOldTVBroadcastMetrics' : ActorMethod<[], undefined>,
  'removeNode' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitTVBroadcastMetrics' : ActorMethod<[TVBroadcastMetrics], undefined>,
  'updateAudioMetrics' : ActorMethod<[AudioMetrics], undefined>,
  'updateCrossChainMetrics' : ActorMethod<[CrossChainMetrics], undefined>,
  'updateCymaticParameters' : ActorMethod<[CymaticParameters], undefined>,
  'updateDHTMetrics' : ActorMethod<
    [string, bigint, boolean, number],
    undefined
  >,
  'updateHumanMetrics' : ActorMethod<[HumanMetrics], undefined>,
  'updateNodeStatus' : ActorMethod<[string, NodeStatus], undefined>,
  'voteOnProposal' : ActorMethod<[bigint, string, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];