/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AudioMetrics = IDL.Record({
  'phaseDrift' : IDL.Float64,
  'amplitude' : IDL.Float64,
  'frequency' : IDL.Float64,
  'entropyNoise' : IDL.Float64,
});
export const CymaticParameters = IDL.Record({
  'uniformData' : IDL.Vec(IDL.Float64),
  'visualPattern' : IDL.Text,
  'intensity' : IDL.Float64,
});
export const NodeStatus = IDL.Variant({
  'active' : IDL.Null,
  'voting' : IDL.Null,
  'inactive' : IDL.Null,
  'participating' : IDL.Null,
});
export const Node = IDL.Record({
  'id' : IDL.Text,
  'status' : NodeStatus,
  'location' : IDL.Text,
});
export const ProposalStatus = IDL.Variant({
  'noConsensus' : IDL.Null,
  'pending' : IDL.Null,
  'crossChainConsensus' : IDL.Null,
  'voting' : IDL.Null,
  'approved' : IDL.Null,
  'tmrConsensus' : IDL.Null,
  'rejected' : IDL.Null,
  'majorityConsensus' : IDL.Null,
});
export const Vote = IDL.Record({ 'nodeId' : IDL.Text, 'accepted' : IDL.Bool });
export const Proposal = IDL.Record({
  'id' : IDL.Nat,
  'status' : ProposalStatus,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'votes' : IDL.Vec(Vote),
  'proposer' : IDL.Principal,
});
export const UserProfile = IDL.Record({
  'nodeId' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
});
export const CrossChainEvent = IDL.Record({
  'timestamp' : IDL.Int,
  'details' : IDL.Text,
  'eventType' : IDL.Text,
});
export const CrossChainMetrics = IDL.Record({
  'chi' : IDL.Float64,
  'phi' : IDL.Float64,
  'theta' : IDL.Float64,
  'inv1' : IDL.Bool,
  'inv2' : IDL.Bool,
  'inv3' : IDL.Bool,
  'inv4' : IDL.Bool,
  'inv5' : IDL.Bool,
  'inv6' : IDL.Bool,
  'chronoflux' : IDL.Float64,
  'rhoAsi' : IDL.Float64,
  'rhoEth' : IDL.Float64,
});
export const TVBroadcastSummary = IDL.Record({
  'status' : IDL.Text,
  'broadcastId' : IDL.Nat,
  'signalStrength' : IDL.Float64,
  'nodeId' : IDL.Text,
  'transmissionQuality' : IDL.Float64,
});
export const DHTMetrics = IDL.Record({
  'dhtScore' : IDL.Float64,
  'merkleVerified' : IDL.Bool,
  'nodeCount' : IDL.Nat,
});
export const EthereumAgent = IDL.Record({
  'checksumValid' : IDL.Bool,
  'address' : IDL.Text,
  'dhtMetrics' : DHTMetrics,
  'entropyScore' : IDL.Float64,
});
export const HumanMetrics = IDL.Record({
  'sandboxActive' : IDL.Bool,
  'intentConfidence' : IDL.Float64,
  'phiDeviation' : IDL.Float64,
  'cognitiveLoad' : IDL.Float64,
});
export const Vector3D = IDL.Record({
  'x' : IDL.Float64,
  'y' : IDL.Float64,
  'z' : IDL.Float64,
});
export const MerkabahSolar = IDL.Record({
  'chiHermetica' : IDL.Float64,
  'tetraedroFeminino' : Vector3D,
  'autisticContinuum' : IDL.Bool,
  'tetraedroMasculino' : Vector3D,
  'ar4366Flux' : IDL.Float64,
});
export const TVBroadcastMetrics = IDL.Record({
  'broadcastId' : IDL.Nat,
  'nodeId' : IDL.Text,
  'frameRate' : IDL.Float64,
  'amplitude' : IDL.Float64,
  'entropy' : IDL.Float64,
  'transmissionQuality' : IDL.Float64,
  'bleStatus' : IDL.Bool,
  'phiIntegrity' : IDL.Float64,
  'timestamp' : IDL.Int,
  'frequency' : IDL.Float64,
  'tmrValidation' : IDL.Bool,
  'pqcStatus' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'activateMerkabahSolar' : IDL.Func([IDL.Float64], [IDL.Float64], []),
  'addEthereumAgent' : IDL.Func([IDL.Text, IDL.Float64, IDL.Bool], [], []),
  'addNode' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProposal' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'generateCymaticParameters' : IDL.Func(
      [AudioMetrics],
      [CymaticParameters],
      [],
    ),
  'getAllNodes' : IDL.Func([], [IDL.Vec(Node)], ['query']),
  'getAllProposals' : IDL.Func([], [IDL.Vec(Proposal)], ['query']),
  'getAllProposalsByTitle' : IDL.Func([], [IDL.Vec(Proposal)], ['query']),
  'getAudioMetrics' : IDL.Func([IDL.Principal], [AudioMetrics], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCrossChainEvents' : IDL.Func([], [IDL.Vec(CrossChainEvent)], ['query']),
  'getCrossChainEventsByType' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CrossChainEvent)],
      ['query'],
    ),
  'getCrossChainMetrics' : IDL.Func([], [CrossChainMetrics], ['query']),
  'getCurrentTVBroadcastSummaries' : IDL.Func(
      [],
      [IDL.Vec(TVBroadcastSummary)],
      ['query'],
    ),
  'getCymaticParameters' : IDL.Func(
      [IDL.Principal],
      [CymaticParameters],
      ['query'],
    ),
  'getEthereumAgent' : IDL.Func([IDL.Text], [EthereumAgent], ['query']),
  'getHumanMetrics' : IDL.Func([IDL.Principal], [HumanMetrics], ['query']),
  'getMerkabahSolarParams' : IDL.Func([], [MerkabahSolar], ['query']),
  'getNode' : IDL.Func([IDL.Text], [Node], ['query']),
  'getProposal' : IDL.Func([IDL.Nat], [Proposal], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logCrossChainEvent' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'pruneOldTVBroadcastMetrics' : IDL.Func([], [], []),
  'removeNode' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitTVBroadcastMetrics' : IDL.Func([TVBroadcastMetrics], [], []),
  'updateAudioMetrics' : IDL.Func([AudioMetrics], [], []),
  'updateCrossChainMetrics' : IDL.Func([CrossChainMetrics], [], []),
  'updateCymaticParameters' : IDL.Func([CymaticParameters], [], []),
  'updateDHTMetrics' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Bool, IDL.Float64],
      [],
      [],
    ),
  'updateHumanMetrics' : IDL.Func([HumanMetrics], [], []),
  'updateNodeStatus' : IDL.Func([IDL.Text, NodeStatus], [], []),
  'voteOnProposal' : IDL.Func([IDL.Nat, IDL.Text, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AudioMetrics = IDL.Record({
    'phaseDrift' : IDL.Float64,
    'amplitude' : IDL.Float64,
    'frequency' : IDL.Float64,
    'entropyNoise' : IDL.Float64,
  });
  const CymaticParameters = IDL.Record({
    'uniformData' : IDL.Vec(IDL.Float64),
    'visualPattern' : IDL.Text,
    'intensity' : IDL.Float64,
  });
  const NodeStatus = IDL.Variant({
    'active' : IDL.Null,
    'voting' : IDL.Null,
    'inactive' : IDL.Null,
    'participating' : IDL.Null,
  });
  const Node = IDL.Record({
    'id' : IDL.Text,
    'status' : NodeStatus,
    'location' : IDL.Text,
  });
  const ProposalStatus = IDL.Variant({
    'noConsensus' : IDL.Null,
    'pending' : IDL.Null,
    'crossChainConsensus' : IDL.Null,
    'voting' : IDL.Null,
    'approved' : IDL.Null,
    'tmrConsensus' : IDL.Null,
    'rejected' : IDL.Null,
    'majorityConsensus' : IDL.Null,
  });
  const Vote = IDL.Record({ 'nodeId' : IDL.Text, 'accepted' : IDL.Bool });
  const Proposal = IDL.Record({
    'id' : IDL.Nat,
    'status' : ProposalStatus,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'votes' : IDL.Vec(Vote),
    'proposer' : IDL.Principal,
  });
  const UserProfile = IDL.Record({
    'nodeId' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
  });
  const CrossChainEvent = IDL.Record({
    'timestamp' : IDL.Int,
    'details' : IDL.Text,
    'eventType' : IDL.Text,
  });
  const CrossChainMetrics = IDL.Record({
    'chi' : IDL.Float64,
    'phi' : IDL.Float64,
    'theta' : IDL.Float64,
    'inv1' : IDL.Bool,
    'inv2' : IDL.Bool,
    'inv3' : IDL.Bool,
    'inv4' : IDL.Bool,
    'inv5' : IDL.Bool,
    'inv6' : IDL.Bool,
    'chronoflux' : IDL.Float64,
    'rhoAsi' : IDL.Float64,
    'rhoEth' : IDL.Float64,
  });
  const TVBroadcastSummary = IDL.Record({
    'status' : IDL.Text,
    'broadcastId' : IDL.Nat,
    'signalStrength' : IDL.Float64,
    'nodeId' : IDL.Text,
    'transmissionQuality' : IDL.Float64,
  });
  const DHTMetrics = IDL.Record({
    'dhtScore' : IDL.Float64,
    'merkleVerified' : IDL.Bool,
    'nodeCount' : IDL.Nat,
  });
  const EthereumAgent = IDL.Record({
    'checksumValid' : IDL.Bool,
    'address' : IDL.Text,
    'dhtMetrics' : DHTMetrics,
    'entropyScore' : IDL.Float64,
  });
  const HumanMetrics = IDL.Record({
    'sandboxActive' : IDL.Bool,
    'intentConfidence' : IDL.Float64,
    'phiDeviation' : IDL.Float64,
    'cognitiveLoad' : IDL.Float64,
  });
  const Vector3D = IDL.Record({
    'x' : IDL.Float64,
    'y' : IDL.Float64,
    'z' : IDL.Float64,
  });
  const MerkabahSolar = IDL.Record({
    'chiHermetica' : IDL.Float64,
    'tetraedroFeminino' : Vector3D,
    'autisticContinuum' : IDL.Bool,
    'tetraedroMasculino' : Vector3D,
    'ar4366Flux' : IDL.Float64,
  });
  const TVBroadcastMetrics = IDL.Record({
    'broadcastId' : IDL.Nat,
    'nodeId' : IDL.Text,
    'frameRate' : IDL.Float64,
    'amplitude' : IDL.Float64,
    'entropy' : IDL.Float64,
    'transmissionQuality' : IDL.Float64,
    'bleStatus' : IDL.Bool,
    'phiIntegrity' : IDL.Float64,
    'timestamp' : IDL.Int,
    'frequency' : IDL.Float64,
    'tmrValidation' : IDL.Bool,
    'pqcStatus' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'activateMerkabahSolar' : IDL.Func([IDL.Float64], [IDL.Float64], []),
    'addEthereumAgent' : IDL.Func([IDL.Text, IDL.Float64, IDL.Bool], [], []),
    'addNode' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProposal' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'generateCymaticParameters' : IDL.Func(
        [AudioMetrics],
        [CymaticParameters],
        [],
      ),
    'getAllNodes' : IDL.Func([], [IDL.Vec(Node)], ['query']),
    'getAllProposals' : IDL.Func([], [IDL.Vec(Proposal)], ['query']),
    'getAllProposalsByTitle' : IDL.Func([], [IDL.Vec(Proposal)], ['query']),
    'getAudioMetrics' : IDL.Func([IDL.Principal], [AudioMetrics], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCrossChainEvents' : IDL.Func([], [IDL.Vec(CrossChainEvent)], ['query']),
    'getCrossChainEventsByType' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CrossChainEvent)],
        ['query'],
      ),
    'getCrossChainMetrics' : IDL.Func([], [CrossChainMetrics], ['query']),
    'getCurrentTVBroadcastSummaries' : IDL.Func(
        [],
        [IDL.Vec(TVBroadcastSummary)],
        ['query'],
      ),
    'getCymaticParameters' : IDL.Func(
        [IDL.Principal],
        [CymaticParameters],
        ['query'],
      ),
    'getEthereumAgent' : IDL.Func([IDL.Text], [EthereumAgent], ['query']),
    'getHumanMetrics' : IDL.Func([IDL.Principal], [HumanMetrics], ['query']),
    'getMerkabahSolarParams' : IDL.Func([], [MerkabahSolar], ['query']),
    'getNode' : IDL.Func([IDL.Text], [Node], ['query']),
    'getProposal' : IDL.Func([IDL.Nat], [Proposal], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logCrossChainEvent' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'pruneOldTVBroadcastMetrics' : IDL.Func([], [], []),
    'removeNode' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitTVBroadcastMetrics' : IDL.Func([TVBroadcastMetrics], [], []),
    'updateAudioMetrics' : IDL.Func([AudioMetrics], [], []),
    'updateCrossChainMetrics' : IDL.Func([CrossChainMetrics], [], []),
    'updateCymaticParameters' : IDL.Func([CymaticParameters], [], []),
    'updateDHTMetrics' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Bool, IDL.Float64],
        [],
        [],
      ),
    'updateHumanMetrics' : IDL.Func([HumanMetrics], [], []),
    'updateNodeStatus' : IDL.Func([IDL.Text, NodeStatus], [], []),
    'voteOnProposal' : IDL.Func([IDL.Nat, IDL.Text, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };