/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    nodeId?: string;
    name: string;
}
export interface CrossChainEvent {
    timestamp: bigint;
    details: string;
    eventType: string;
}
export interface Vector3D {
    x: number;
    y: number;
    z: number;
}
export interface Proposal {
    id: bigint;
    status: ProposalStatus;
    title: string;
    content: string;
    votes: Array<Vote>;
    proposer: Principal;
}
export interface EthereumAgent {
    checksumValid: boolean;
    address: string;
    dhtMetrics: DHTMetrics;
    entropyScore: number;
}
export interface TVBroadcastSummary {
    status: string;
    broadcastId: bigint;
    signalStrength: number;
    nodeId: string;
    transmissionQuality: number;
}
export interface HumanMetrics {
    sandboxActive: boolean;
    intentConfidence: number;
    phiDeviation: number;
    cognitiveLoad: number;
}
export interface Node {
    id: string;
    status: NodeStatus;
    location: string;
}
export interface CymaticParameters {
    uniformData: Array<number>;
    visualPattern: string;
    intensity: number;
}
export interface CrossChainMetrics {
    chi: number;
    phi: number;
    theta: number;
    inv1: boolean;
    inv2: boolean;
    inv3: boolean;
    inv4: boolean;
    inv5: boolean;
    inv6: boolean;
    chronoflux: number;
    rhoAsi: number;
    rhoEth: number;
}
export interface AudioMetrics {
    phaseDrift: number;
    amplitude: number;
    frequency: number;
    entropyNoise: number;
}
export interface Vote {
    nodeId: string;
    accepted: boolean;
}
export interface MerkabahSolar {
    chiHermetica: number;
    tetraedroFeminino: Vector3D;
    autisticContinuum: boolean;
    tetraedroMasculino: Vector3D;
    ar4366Flux: number;
}
export interface DHTMetrics {
    dhtScore: number;
    merkleVerified: boolean;
    nodeCount: bigint;
}
export interface TVBroadcastMetrics {
    broadcastId: bigint;
    nodeId: string;
    frameRate: number;
    amplitude: number;
    entropy: number;
    transmissionQuality: number;
    bleStatus: boolean;
    phiIntegrity: number;
    timestamp: bigint;
    frequency: number;
    tmrValidation: boolean;
    pqcStatus: boolean;
}
export enum NodeStatus {
    active = "active",
    voting = "voting",
    inactive = "inactive",
    participating = "participating"
}
export enum ProposalStatus {
    noConsensus = "noConsensus",
    pending = "pending",
    crossChainConsensus = "crossChainConsensus",
    voting = "voting",
    approved = "approved",
    tmrConsensus = "tmrConsensus",
    rejected = "rejected",
    majorityConsensus = "majorityConsensus"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    activateMerkabahSolar(intention: number): Promise<number>;
    addEthereumAgent(address: string, entropyScore: number, checksumValid: boolean): Promise<void>;
    addNode(nodeId: string, location: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createProposal(title: string, content: string): Promise<bigint>;
    generateCymaticParameters(audioMetrics: AudioMetrics): Promise<CymaticParameters>;
    getAllNodes(): Promise<Array<Node>>;
    getAllProposals(): Promise<Array<Proposal>>;
    getAllProposalsByTitle(): Promise<Array<Proposal>>;
    getAudioMetrics(user: Principal): Promise<AudioMetrics>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCrossChainEvents(): Promise<Array<CrossChainEvent>>;
    getCrossChainEventsByType(eventType: string): Promise<Array<CrossChainEvent>>;
    getCrossChainMetrics(): Promise<CrossChainMetrics>;
    getCurrentTVBroadcastSummaries(): Promise<Array<TVBroadcastSummary>>;
    getCymaticParameters(user: Principal): Promise<CymaticParameters>;
    getEthereumAgent(address: string): Promise<EthereumAgent>;
    getHumanMetrics(user: Principal): Promise<HumanMetrics>;
    getMerkabahSolarParams(): Promise<MerkabahSolar>;
    getNode(nodeId: string): Promise<Node>;
    getProposal(proposalId: bigint): Promise<Proposal>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    logCrossChainEvent(eventType: string, details: string): Promise<void>;
    pruneOldTVBroadcastMetrics(): Promise<void>;
    removeNode(nodeId: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitTVBroadcastMetrics(metrics: TVBroadcastMetrics): Promise<void>;
    updateAudioMetrics(metrics: AudioMetrics): Promise<void>;
    updateCrossChainMetrics(metrics: CrossChainMetrics): Promise<void>;
    updateCymaticParameters(params: CymaticParameters): Promise<void>;
    updateDHTMetrics(address: string, nodeCount: bigint, merkleVerified: boolean, dhtScore: number): Promise<void>;
    updateHumanMetrics(metrics: HumanMetrics): Promise<void>;
    updateNodeStatus(nodeId: string, status: NodeStatus): Promise<void>;
    voteOnProposal(proposalId: bigint, nodeId: string, accepted: boolean): Promise<void>;
}
import type { Node as _Node, NodeStatus as _NodeStatus, Proposal as _Proposal, ProposalStatus as _ProposalStatus, UserProfile as _UserProfile, UserRole as _UserRole, Vote as _Vote } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async activateMerkabahSolar(arg0: number): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.activateMerkabahSolar(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.activateMerkabahSolar(arg0);
            return result;
        }
    }
    async addEthereumAgent(arg0: string, arg1: number, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addEthereumAgent(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEthereumAgent(arg0, arg1, arg2);
            return result;
        }
    }
    async addNode(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addNode(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNode(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createProposal(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createProposal(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProposal(arg0, arg1);
            return result;
        }
    }
    async generateCymaticParameters(arg0: AudioMetrics): Promise<CymaticParameters> {
        if (this.processError) {
            try {
                const result = await this.actor.generateCymaticParameters(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateCymaticParameters(arg0);
            return result;
        }
    }
    async getAllNodes(): Promise<Array<Node>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNodes();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNodes();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProposals(): Promise<Array<Proposal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProposals();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProposals();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProposalsByTitle(): Promise<Array<Proposal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProposalsByTitle();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProposalsByTitle();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAudioMetrics(arg0: Principal): Promise<AudioMetrics> {
        if (this.processError) {
            try {
                const result = await this.actor.getAudioMetrics(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAudioMetrics(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCrossChainEvents(): Promise<Array<CrossChainEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCrossChainEvents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCrossChainEvents();
            return result;
        }
    }
    async getCrossChainEventsByType(arg0: string): Promise<Array<CrossChainEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCrossChainEventsByType(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCrossChainEventsByType(arg0);
            return result;
        }
    }
    async getCrossChainMetrics(): Promise<CrossChainMetrics> {
        if (this.processError) {
            try {
                const result = await this.actor.getCrossChainMetrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCrossChainMetrics();
            return result;
        }
    }
    async getCurrentTVBroadcastSummaries(): Promise<Array<TVBroadcastSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentTVBroadcastSummaries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentTVBroadcastSummaries();
            return result;
        }
    }
    async getCymaticParameters(arg0: Principal): Promise<CymaticParameters> {
        if (this.processError) {
            try {
                const result = await this.actor.getCymaticParameters(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCymaticParameters(arg0);
            return result;
        }
    }
    async getEthereumAgent(arg0: string): Promise<EthereumAgent> {
        if (this.processError) {
            try {
                const result = await this.actor.getEthereumAgent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEthereumAgent(arg0);
            return result;
        }
    }
    async getHumanMetrics(arg0: Principal): Promise<HumanMetrics> {
        if (this.processError) {
            try {
                const result = await this.actor.getHumanMetrics(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHumanMetrics(arg0);
            return result;
        }
    }
    async getMerkabahSolarParams(): Promise<MerkabahSolar> {
        if (this.processError) {
            try {
                const result = await this.actor.getMerkabahSolarParams();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMerkabahSolarParams();
            return result;
        }
    }
    async getNode(arg0: string): Promise<Node> {
        if (this.processError) {
            try {
                const result = await this.actor.getNode(arg0);
                return from_candid_Node_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNode(arg0);
            return from_candid_Node_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProposal(arg0: bigint): Promise<Proposal> {
        if (this.processError) {
            try {
                const result = await this.actor.getProposal(arg0);
                return from_candid_Proposal_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProposal(arg0);
            return from_candid_Proposal_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async logCrossChainEvent(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logCrossChainEvent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logCrossChainEvent(arg0, arg1);
            return result;
        }
    }
    async pruneOldTVBroadcastMetrics(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.pruneOldTVBroadcastMetrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.pruneOldTVBroadcastMetrics();
            return result;
        }
    }
    async removeNode(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeNode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeNode(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitTVBroadcastMetrics(arg0: TVBroadcastMetrics): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitTVBroadcastMetrics(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitTVBroadcastMetrics(arg0);
            return result;
        }
    }
    async updateAudioMetrics(arg0: AudioMetrics): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAudioMetrics(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAudioMetrics(arg0);
            return result;
        }
    }
    async updateCrossChainMetrics(arg0: CrossChainMetrics): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCrossChainMetrics(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCrossChainMetrics(arg0);
            return result;
        }
    }
    async updateCymaticParameters(arg0: CymaticParameters): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCymaticParameters(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCymaticParameters(arg0);
            return result;
        }
    }
    async updateDHTMetrics(arg0: string, arg1: bigint, arg2: boolean, arg3: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDHTMetrics(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDHTMetrics(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateHumanMetrics(arg0: HumanMetrics): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHumanMetrics(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHumanMetrics(arg0);
            return result;
        }
    }
    async updateNodeStatus(arg0: string, arg1: NodeStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNodeStatus(arg0, to_candid_NodeStatus_n21(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNodeStatus(arg0, to_candid_NodeStatus_n21(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async voteOnProposal(arg0: bigint, arg1: string, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.voteOnProposal(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.voteOnProposal(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_NodeStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NodeStatus): NodeStatus {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Node_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Node): Node {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_ProposalStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProposalStatus): ProposalStatus {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Proposal_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Proposal): Proposal {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ProposalStatus;
    title: string;
    content: string;
    votes: Array<_Vote>;
    proposer: Principal;
}): {
    id: bigint;
    status: ProposalStatus;
    title: string;
    content: string;
    votes: Array<Vote>;
    proposer: Principal;
} {
    return {
        id: value.id,
        status: from_candid_ProposalStatus_n11(_uploadFile, _downloadFile, value.status),
        title: value.title,
        content: value.content,
        votes: value.votes,
        proposer: value.proposer
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nodeId: [] | [string];
    name: string;
}): {
    nodeId?: string;
    name: string;
} {
    return {
        nodeId: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.nodeId)),
        name: value.name
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _NodeStatus;
    location: string;
}): {
    id: string;
    status: NodeStatus;
    location: string;
} {
    return {
        id: value.id,
        status: from_candid_NodeStatus_n6(_uploadFile, _downloadFile, value.status),
        location: value.location
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    noConsensus: null;
} | {
    pending: null;
} | {
    crossChainConsensus: null;
} | {
    voting: null;
} | {
    approved: null;
} | {
    tmrConsensus: null;
} | {
    rejected: null;
} | {
    majorityConsensus: null;
}): ProposalStatus {
    return "noConsensus" in value ? ProposalStatus.noConsensus : "pending" in value ? ProposalStatus.pending : "crossChainConsensus" in value ? ProposalStatus.crossChainConsensus : "voting" in value ? ProposalStatus.voting : "approved" in value ? ProposalStatus.approved : "tmrConsensus" in value ? ProposalStatus.tmrConsensus : "rejected" in value ? ProposalStatus.rejected : "majorityConsensus" in value ? ProposalStatus.majorityConsensus : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    voting: null;
} | {
    inactive: null;
} | {
    participating: null;
}): NodeStatus {
    return "active" in value ? NodeStatus.active : "voting" in value ? NodeStatus.voting : "inactive" in value ? NodeStatus.inactive : "participating" in value ? NodeStatus.participating : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Node>): Array<Node> {
    return value.map((x)=>from_candid_Node_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Proposal>): Array<Proposal> {
    return value.map((x)=>from_candid_Proposal_n9(_uploadFile, _downloadFile, x));
}
function to_candid_NodeStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NodeStatus): _NodeStatus {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nodeId?: string;
    name: string;
}): {
    nodeId: [] | [string];
    name: string;
} {
    return {
        nodeId: value.nodeId ? candid_some(value.nodeId) : candid_none(),
        name: value.name
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NodeStatus): {
    active: null;
} | {
    voting: null;
} | {
    inactive: null;
} | {
    participating: null;
} {
    return value == NodeStatus.active ? {
        active: null
    } : value == NodeStatus.voting ? {
        voting: null
    } : value == NodeStatus.inactive ? {
        inactive: null
    } : value == NodeStatus.participating ? {
        participating: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
